name: big_cart
description: "Sample app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  bloc_concurrency: ^0.3.0
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  dartz: ^0.10.1
  get_it: ^9.2.1
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.5
  build_runner: ^2.15.1
  injectable: ^3.0.0
  json_serializable: ^6.14.0
  dio: ^5.11.0
  flutter_screenutil_plus: ^1.5.0
  google_fonts: ^8.2.0
  smooth_page_indicator: ^2.0.1
  flutter_svg: ^2.3.0
  intl_phone_number_input: ^0.7.5
  pinput: ^6.0.2
  flutter_rating_bar_plus: ^4.0.2
  intl: ^0.20.3
  country_picker: ^2.0.28
  timeago: ^3.7.1
  flutter_slidable: ^4.0.3
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/green_bag.jpg
    - assets/logo.png    
    - assets/eggs.jpg
    - assets/apple.jpg
    - assets/lemon_bag.jpg
    - assets/woman_cart.jpg
    - assets/woman_freezer.jpg
    - assets/woman_happy.jpg
    - assets/google_logo.svg
    - assets/discount.jpg
    - assets/apple.png
    - assets/lettuce.png
    - assets/vacuum-cleaner.png
    - assets/apple-cider.png
    - assets/olive-oil.png
    - assets/vegetable.png
    - assets/baby-bottle.png
    - assets/avocado.png
    - assets/peach.png
    - assets/grapes.png
    - assets/pineapple.png
    - assets/broccoli.png
    - assets/pomegranate.png
    - assets/blank_profile_picture.png
    - assets/profile_picture.jpg
    - assets/mastercard.png
    - assets/visa.png
    - assets/paypal.png
    - assets/card_picture.png

        
